//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace GUI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class kladionicaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new kladionicaEntities object using the connection string found in the 'kladionicaEntities' section of the application configuration file.
        /// </summary>
        public kladionicaEntities() : base("name=kladionicaEntities", "kladionicaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kladionicaEntities object.
        /// </summary>
        public kladionicaEntities(string connectionString) : base(connectionString, "kladionicaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new kladionicaEntities object.
        /// </summary>
        public kladionicaEntities(EntityConnection connection) : base(connection, "kladionicaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dogadjaji> dogadjaji
        {
            get
            {
                if ((_dogadjaji == null))
                {
                    _dogadjaji = base.CreateObjectSet<dogadjaji>("dogadjaji");
                }
                return _dogadjaji;
            }
        }
        private ObjectSet<dogadjaji> _dogadjaji;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dogadjaji EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodogadjaji(dogadjaji dogadjaji)
        {
            base.AddObject("dogadjaji", dogadjaji);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kladionicaModel", Name="dogadjaji")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dogadjaji : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dogadjaji object.
        /// </summary>
        /// <param name="idDogadjaja">Initial value of the IdDogadjaja property.</param>
        public static dogadjaji Createdogadjaji(global::System.Decimal idDogadjaja)
        {
            dogadjaji dogadjaji = new dogadjaji();
            dogadjaji.IdDogadjaja = idDogadjaja;
            return dogadjaji;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImePU
        {
            get
            {
                return _ImePU;
            }
            set
            {
                OnImePUChanging(value);
                ReportPropertyChanging("ImePU");
                _ImePU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImePU");
                OnImePUChanged();
            }
        }
        private global::System.String _ImePU;
        partial void OnImePUChanging(global::System.String value);
        partial void OnImePUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImeDU
        {
            get
            {
                return _ImeDU;
            }
            set
            {
                OnImeDUChanging(value);
                ReportPropertyChanging("ImeDU");
                _ImeDU = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImeDU");
                OnImeDUChanged();
            }
        }
        private global::System.String _ImeDU;
        partial void OnImeDUChanging(global::System.String value);
        partial void OnImeDUChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Kvota1
        {
            get
            {
                return _Kvota1;
            }
            set
            {
                OnKvota1Changing(value);
                ReportPropertyChanging("Kvota1");
                _Kvota1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kvota1");
                OnKvota1Changed();
            }
        }
        private Nullable<global::System.Decimal> _Kvota1;
        partial void OnKvota1Changing(Nullable<global::System.Decimal> value);
        partial void OnKvota1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> KvotaX
        {
            get
            {
                return _KvotaX;
            }
            set
            {
                OnKvotaXChanging(value);
                ReportPropertyChanging("KvotaX");
                _KvotaX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KvotaX");
                OnKvotaXChanged();
            }
        }
        private Nullable<global::System.Decimal> _KvotaX;
        partial void OnKvotaXChanging(Nullable<global::System.Decimal> value);
        partial void OnKvotaXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Kvota2
        {
            get
            {
                return _Kvota2;
            }
            set
            {
                OnKvota2Changing(value);
                ReportPropertyChanging("Kvota2");
                _Kvota2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kvota2");
                OnKvota2Changed();
            }
        }
        private Nullable<global::System.Decimal> _Kvota2;
        partial void OnKvota2Changing(Nullable<global::System.Decimal> value);
        partial void OnKvota2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Kvota1X
        {
            get
            {
                return _Kvota1X;
            }
            set
            {
                OnKvota1XChanging(value);
                ReportPropertyChanging("Kvota1X");
                _Kvota1X = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kvota1X");
                OnKvota1XChanged();
            }
        }
        private Nullable<global::System.Decimal> _Kvota1X;
        partial void OnKvota1XChanging(Nullable<global::System.Decimal> value);
        partial void OnKvota1XChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> KvotaX2
        {
            get
            {
                return _KvotaX2;
            }
            set
            {
                OnKvotaX2Changing(value);
                ReportPropertyChanging("KvotaX2");
                _KvotaX2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KvotaX2");
                OnKvotaX2Changed();
            }
        }
        private Nullable<global::System.Decimal> _KvotaX2;
        partial void OnKvotaX2Changing(Nullable<global::System.Decimal> value);
        partial void OnKvotaX2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Kvota12
        {
            get
            {
                return _Kvota12;
            }
            set
            {
                OnKvota12Changing(value);
                ReportPropertyChanging("Kvota12");
                _Kvota12 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kvota12");
                OnKvota12Changed();
            }
        }
        private Nullable<global::System.Decimal> _Kvota12;
        partial void OnKvota12Changing(Nullable<global::System.Decimal> value);
        partial void OnKvota12Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rezultat
        {
            get
            {
                return _Rezultat;
            }
            set
            {
                OnRezultatChanging(value);
                ReportPropertyChanging("Rezultat");
                _Rezultat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rezultat");
                OnRezultatChanged();
            }
        }
        private Nullable<global::System.Int32> _Rezultat;
        partial void OnRezultatChanging(Nullable<global::System.Int32> value);
        partial void OnRezultatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DatumOdrzavanja
        {
            get
            {
                return _DatumOdrzavanja;
            }
            set
            {
                OnDatumOdrzavanjaChanging(value);
                ReportPropertyChanging("DatumOdrzavanja");
                _DatumOdrzavanja = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DatumOdrzavanja");
                OnDatumOdrzavanjaChanged();
            }
        }
        private global::System.String _DatumOdrzavanja;
        partial void OnDatumOdrzavanjaChanging(global::System.String value);
        partial void OnDatumOdrzavanjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SatnicaOdrzavanja
        {
            get
            {
                return _SatnicaOdrzavanja;
            }
            set
            {
                OnSatnicaOdrzavanjaChanging(value);
                ReportPropertyChanging("SatnicaOdrzavanja");
                _SatnicaOdrzavanja = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SatnicaOdrzavanja");
                OnSatnicaOdrzavanjaChanged();
            }
        }
        private Nullable<global::System.Int32> _SatnicaOdrzavanja;
        partial void OnSatnicaOdrzavanjaChanging(Nullable<global::System.Int32> value);
        partial void OnSatnicaOdrzavanjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IdDogadjaja
        {
            get
            {
                return _IdDogadjaja;
            }
            set
            {
                if (_IdDogadjaja != value)
                {
                    OnIdDogadjajaChanging(value);
                    ReportPropertyChanging("IdDogadjaja");
                    _IdDogadjaja = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDogadjaja");
                    OnIdDogadjajaChanged();
                }
            }
        }
        private global::System.Decimal _IdDogadjaja;
        partial void OnIdDogadjajaChanging(global::System.Decimal value);
        partial void OnIdDogadjajaChanged();

        #endregion
    
    }

    #endregion
    
}
